package com.fallout.fallout.model;

public enum Room {
    VAULT_DOOR, LIVING_ROOM, POWER_GENERATOR, DINER, WATER_TREATMENT,
    STORAGE_ROOM, MEDBAY, SCIENCE_LAB, OVERSEERS_OFFICE, RADIO_STUDIO,
    WEAPON_WORKKSHOP, WEIGHT_ROOM, aTHLETICS_ROOM, ARMORY, CLASSROOM,
    OUTFIT_WORKSHOP, FITNESS_ROOM, LOUNGE, THEME_WORKSHOP, GAME_ROOM,
    BARBERSHOP, NUCLEAR_REACTOR, GARDEN, WATER_PURIFICATION,
    NUKA_COLA_BOTTLER
}
